#Blocks that should be ignored when considering what counts as a collision
nonSolidBlocks:
  - AIR #Game will not function correctly if this is removed
  - PLAYER_HEAD #Game will not function correctly if this is removed

#Song path
song-file-path: "plugins/Snake/songs/song.nbs"

#Region names
Lobby: lobby
Gamezone: gamezone

#Lobby and GameZone teleportation points
teleportLocations:
  game:
    x:
    y:
    z:
  lobby:
    x:
    y:
    z:

#World that the game should be running in
world: world

# Speed of the snake (e.g., 10 ticks)
snake-speed: 10

#Toggle wolfchase option, off by default
wolfchase: false
