# Minecraft Snake Game Plugin Configuration

# Music Settings
# Enable or disable in-game music playback.
# Useful if you have NoteblockAPI for another plugin but wish to disable music for this game.
# This setting will have no effect if NoteblockAPI is not installed.
# Default value: true
enable-music: true

# Path to the song file for in-game music.
# This setting will have no effect if NoteblockAPI is not installed.
# Default path: "songs/song.nbs"
song-file-path: "songs/song.nbs"

# Gameplay Settings
# Speed of the snake in blocks per second.
# Some speed values may cause unexpected behavior. Please exercise caution when adjusting this value.
# Default value: 5.0
snake-speed: 5.0

# Maximum number of players allowed per game zone.
# Increasing this value allows more players to participate in a single game zone.
# A value of at least 1 is required. Setting this value to 0 will prevent players from entering games.
# Default value: 1
max-players-per-game: 1

# Maximum number of apples that can spawn simultaneously per game.
# Increasing this value will make more apples available at once.
# A value of at least 1 is required. Setting this value to 0 will prevent apples from spawning.
# Default value: 1
max-apples-per-game: 1

# Advanced Settings
# Distance before a segment is forcefully teleported back to its waypoint.
# A value of at least 1.2 is recommended, higher values increase the length segments can separate before being teleported.
# Default value: 1.2
force-teleport-distance: 1.2

# Distance threshold for determining if the snake's head is close enough to its target waypoint.
# Increasing this may help with higher speeds at the cost of segment de-synchronization.
# Default value: 0.1
target-close-enough-distance: 0.1