name: Snake
version: '${version}'
main: com.slimer.Main.Main
authors: [Slimerblue22]
api-version: '1.20'
load: POSTWORLD
depend: [ProtocolLib, WorldGuard]
softdepend: [NoteBlockAPI]
commands:
  snakeadmin:
    description: Admin command for the Snake game plugin
    aliases: [sa]
  snakegame:
    description: Command for controlling the Snake game
    aliases: [sg]
permissions:
  snake.admin:
    description: Permission for the Snake game admin commands
    default: op
  snake.play:
    description: Permission for playing the Snake game
    default: op
