name: Snake
version: '${version}'
main: com.slimer.Main.Main
authors: [Slimerblue22]
api-version: '1.20'
load: POSTWORLD
depend: [ProtocolLib, WorldGuard]
softdepend: [NoteBlockAPI]
commands:
  snakeregion:
    description: Command for controlling the region system
    aliases: [sr]
  snakegame:
    description: Command for using general game commands and to play a game of snake
    aliases: [sg]
  snakedebug:
    description: Command for controlling the debug system
    aliases: [sd]
permissions:
  snake.admin:
    description: Permission for the region and debug commands
    default: op
  snake.play:
    description: Permission for playing the Snake game
    default: op
